# Generated by Django 4.2.6 on 2023-11-06 05:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_managers_rename_id_user_userid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sportId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sportName', models.CharField(max_length=32, unique=True)),
                ('sportDescription', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Sport',
            },
        ),
        migrations.CreateModel(
            name='SportRecord',
            fields=[
                ('sportRecordId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('sportId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sport')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'SportRecord',
            },
        ),
    ]
