# Generated by Django 4.2.6 on 2023-11-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sport_sportrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Team',
            },
        ),
        migrations.AddField(
            model_name='sport',
            name='sportCoverName',
            field=models.CharField(default='defaultSportCover.jpg', max_length=64),
        ),
    ]
