# Generated by Django 4.2.6 on 2023-11-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_article_update_at_alter_article_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='有趣的文章~', max_length=128),
        ),
    ]
