# Generated by Django 4.2.6 on 2023-11-09 15:28

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='createPerson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='team',
            name='createTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team',
            name='curPersonCnt',
            field=models.IntegerField(default=1, validators=[api.models.validate_cur_person_lte_max_person]),
        ),
        migrations.AddField(
            model_name='team',
            name='endTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team',
            name='maxPerson',
            field=models.IntegerField(default=8, validators=[api.models.validate_max_person_greater_than_2]),
        ),
        migrations.AddField(
            model_name='team',
            name='sportType',
            field=models.ForeignKey(default='其他运动', on_delete=django.db.models.deletion.CASCADE, to='api.sport', to_field='sportName'),
        ),
        migrations.AddField(
            model_name='team',
            name='teamState',
            field=models.CharField(choices=[('R', 'RENEW'), ('O', 'ON'), ('E', 'END')], max_length=1, null=True),
        ),
    ]
