# Generated by Django 4.2.6 on 2023-11-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_team_createperson_team_createtime_team_curpersoncnt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamName',
            field=models.CharField(default='kossur', max_length=128, unique=True),
        ),
    ]
