# Generated by Django 4.2.6 on 2023-11-11 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='startTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
